# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Mohammed Sarfarazuddin
title: Data Scientist/Analyst and an Astrophysicist 
email: shahruq.sarfaraz@gmail.com

# Social links
github_username:  shahruq
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: shahruqsarfaraz
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
• A 24-year-old graduate from India with an MSc in Astrophysics (with a research thesis in Machine Learning/Deep Learning for Astronomy) with 18 months of experience with handling data. 
• I am seeking a role in Data – Analyst/Data/Pricing Analyst, Data Scientist or any position within an organization which can let me handle data, summon insights and pitch them out using my presentation and communication skills.
• I have an intermediate amount of experience in Data Analysis and Machine Learning with R scripting and Python programming language. 
• The highlight of my education so far is demonstrating and implementing the importance of Machine Learning in the field of Astronomy.
• I have maintained, implemented and described ‘root-cause analysis’ using text mining and ML for a real-life dataset. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
